# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master/build/CMakeFiles /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lburg

# Build rule for target.
lburg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lburg
.PHONY : lburg

# fast build rule for target.
lburg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/build
.PHONY : lburg/fast

#=============================================================================
# Target rules for targets named cpp

# Build rule for target.
cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp
.PHONY : cpp

# fast build rule for target.
cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/build
.PHONY : cpp/fast

#=============================================================================
# Target rules for targets named rcc

# Build rule for target.
rcc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rcc
.PHONY : rcc

# fast build rule for target.
rcc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/build
.PHONY : rcc/fast

#=============================================================================
# Target rules for targets named lcc

# Build rule for target.
lcc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lcc
.PHONY : lcc

# fast build rule for target.
lcc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/build
.PHONY : lcc/fast

#=============================================================================
# Target rules for targets named gtsim

# Build rule for target.
gtsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtsim
.PHONY : gtsim

# fast build rule for target.
gtsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gtsim.dir/build.make CMakeFiles/gtsim.dir/build
.PHONY : gtsim/fast

#=============================================================================
# Target rules for targets named glcc-ready

# Build rule for target.
glcc-ready: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glcc-ready
.PHONY : glcc-ready

# fast build rule for target.
glcc-ready/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glcc-ready.dir/build.make CMakeFiles/glcc-ready.dir/build
.PHONY : glcc-ready/fast

#=============================================================================
# Target rules for targets named map128k

# Build rule for target.
map128k: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map128k
.PHONY : map128k

# fast build rule for target.
map128k/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/map128k.dir/build.make CMakeFiles/map128k.dir/build
.PHONY : map128k/fast

#=============================================================================
# Target rules for targets named map32k

# Build rule for target.
map32k: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map32k
.PHONY : map32k

# fast build rule for target.
map32k/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/map32k.dir/build.make CMakeFiles/map32k.dir/build
.PHONY : map32k/fast

#=============================================================================
# Target rules for targets named map512k

# Build rule for target.
map512k: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map512k
.PHONY : map512k

# fast build rule for target.
map512k/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/map512k.dir/build.make CMakeFiles/map512k.dir/build
.PHONY : map512k/fast

#=============================================================================
# Target rules for targets named map64k

# Build rule for target.
map64k: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 map64k
.PHONY : map64k

# fast build rule for target.
map64k/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/map64k.dir/build.make CMakeFiles/map64k.dir/build
.PHONY : map64k/fast

#=============================================================================
# Target rules for targets named mapconx

# Build rule for target.
mapconx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mapconx
.PHONY : mapconx

# fast build rule for target.
mapconx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mapconx.dir/build.make CMakeFiles/mapconx.dir/build
.PHONY : mapconx/fast

#=============================================================================
# Target rules for targets named mapsim

# Build rule for target.
mapsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mapsim
.PHONY : mapsim

# fast build rule for target.
mapsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mapsim.dir/build.make CMakeFiles/mapsim.dir/build
.PHONY : mapsim/fast

#=============================================================================
# Target rules for targets named libconx

# Build rule for target.
libconx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libconx
.PHONY : libconx

# fast build rule for target.
libconx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libconx.dir/build.make CMakeFiles/libconx.dir/build
.PHONY : libconx/fast

#=============================================================================
# Target rules for targets named libcon_b

# Build rule for target.
libcon_b: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcon_b
.PHONY : libcon_b

# fast build rule for target.
libcon_b/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcon_b.dir/build.make CMakeFiles/libcon_b.dir/build
.PHONY : libcon_b/fast

#=============================================================================
# Target rules for targets named libcon_n

# Build rule for target.
libcon_n: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcon_n
.PHONY : libcon_n

# fast build rule for target.
libcon_n/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcon_n.dir/build.make CMakeFiles/libcon_n.dir/build
.PHONY : libcon_n/fast

#=============================================================================
# Target rules for targets named libcon_h

# Build rule for target.
libcon_h: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcon_h
.PHONY : libcon_h

# fast build rule for target.
libcon_h/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcon_h.dir/build.make CMakeFiles/libcon_h.dir/build
.PHONY : libcon_h/fast

#=============================================================================
# Target rules for targets named libcon1

# Build rule for target.
libcon1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcon1
.PHONY : libcon1

# fast build rule for target.
libcon1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcon1.dir/build.make CMakeFiles/libcon1.dir/build
.PHONY : libcon1/fast

#=============================================================================
# Target rules for targets named libsim

# Build rule for target.
libsim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libsim
.PHONY : libsim

# fast build rule for target.
libsim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libsim.dir/build.make CMakeFiles/libsim.dir/build
.PHONY : libsim/fast

#=============================================================================
# Target rules for targets named libc-cpu4

# Build rule for target.
libc-cpu4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libc-cpu4
.PHONY : libc-cpu4

# fast build rule for target.
libc-cpu4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libc-cpu4.dir/build.make CMakeFiles/libc-cpu4.dir/build
.PHONY : libc-cpu4/fast

#=============================================================================
# Target rules for targets named libc-cpu5

# Build rule for target.
libc-cpu5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libc-cpu5
.PHONY : libc-cpu5

# fast build rule for target.
libc-cpu5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libc-cpu5.dir/build.make CMakeFiles/libc-cpu5.dir/build
.PHONY : libc-cpu5/fast

#=============================================================================
# Target rules for targets named libc-cpu6

# Build rule for target.
libc-cpu6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libc-cpu6
.PHONY : libc-cpu6

# fast build rule for target.
libc-cpu6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libc-cpu6.dir/build.make CMakeFiles/libc-cpu6.dir/build
.PHONY : libc-cpu6/fast

#=============================================================================
# Target rules for targets named libc-cpu7

# Build rule for target.
libc-cpu7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libc-cpu7
.PHONY : libc-cpu7

# fast build rule for target.
libc-cpu7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libc-cpu7.dir/build.make CMakeFiles/libc-cpu7.dir/build
.PHONY : libc-cpu7/fast

alpha.o: alpha.c.o
.PHONY : alpha.o

# target to build an object file
alpha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/alpha.c.o
.PHONY : alpha.c.o

alpha.i: alpha.c.i
.PHONY : alpha.i

# target to preprocess a source file
alpha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/alpha.c.i
.PHONY : alpha.c.i

alpha.s: alpha.c.s
.PHONY : alpha.s

# target to generate assembly for a file
alpha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/alpha.c.s
.PHONY : alpha.c.s

cpp/cpp.o: cpp/cpp.c.o
.PHONY : cpp/cpp.o

# target to build an object file
cpp/cpp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/cpp.c.o
.PHONY : cpp/cpp.c.o

cpp/cpp.i: cpp/cpp.c.i
.PHONY : cpp/cpp.i

# target to preprocess a source file
cpp/cpp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/cpp.c.i
.PHONY : cpp/cpp.c.i

cpp/cpp.s: cpp/cpp.c.s
.PHONY : cpp/cpp.s

# target to generate assembly for a file
cpp/cpp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/cpp.c.s
.PHONY : cpp/cpp.c.s

cpp/eval.o: cpp/eval.c.o
.PHONY : cpp/eval.o

# target to build an object file
cpp/eval.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/eval.c.o
.PHONY : cpp/eval.c.o

cpp/eval.i: cpp/eval.c.i
.PHONY : cpp/eval.i

# target to preprocess a source file
cpp/eval.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/eval.c.i
.PHONY : cpp/eval.c.i

cpp/eval.s: cpp/eval.c.s
.PHONY : cpp/eval.s

# target to generate assembly for a file
cpp/eval.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/eval.c.s
.PHONY : cpp/eval.c.s

cpp/getopt.o: cpp/getopt.c.o
.PHONY : cpp/getopt.o

# target to build an object file
cpp/getopt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/getopt.c.o
.PHONY : cpp/getopt.c.o

cpp/getopt.i: cpp/getopt.c.i
.PHONY : cpp/getopt.i

# target to preprocess a source file
cpp/getopt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/getopt.c.i
.PHONY : cpp/getopt.c.i

cpp/getopt.s: cpp/getopt.c.s
.PHONY : cpp/getopt.s

# target to generate assembly for a file
cpp/getopt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/getopt.c.s
.PHONY : cpp/getopt.c.s

cpp/hideset.o: cpp/hideset.c.o
.PHONY : cpp/hideset.o

# target to build an object file
cpp/hideset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/hideset.c.o
.PHONY : cpp/hideset.c.o

cpp/hideset.i: cpp/hideset.c.i
.PHONY : cpp/hideset.i

# target to preprocess a source file
cpp/hideset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/hideset.c.i
.PHONY : cpp/hideset.c.i

cpp/hideset.s: cpp/hideset.c.s
.PHONY : cpp/hideset.s

# target to generate assembly for a file
cpp/hideset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/hideset.c.s
.PHONY : cpp/hideset.c.s

cpp/include.o: cpp/include.c.o
.PHONY : cpp/include.o

# target to build an object file
cpp/include.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/include.c.o
.PHONY : cpp/include.c.o

cpp/include.i: cpp/include.c.i
.PHONY : cpp/include.i

# target to preprocess a source file
cpp/include.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/include.c.i
.PHONY : cpp/include.c.i

cpp/include.s: cpp/include.c.s
.PHONY : cpp/include.s

# target to generate assembly for a file
cpp/include.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/include.c.s
.PHONY : cpp/include.c.s

cpp/lex.o: cpp/lex.c.o
.PHONY : cpp/lex.o

# target to build an object file
cpp/lex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/lex.c.o
.PHONY : cpp/lex.c.o

cpp/lex.i: cpp/lex.c.i
.PHONY : cpp/lex.i

# target to preprocess a source file
cpp/lex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/lex.c.i
.PHONY : cpp/lex.c.i

cpp/lex.s: cpp/lex.c.s
.PHONY : cpp/lex.s

# target to generate assembly for a file
cpp/lex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/lex.c.s
.PHONY : cpp/lex.c.s

cpp/macro.o: cpp/macro.c.o
.PHONY : cpp/macro.o

# target to build an object file
cpp/macro.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/macro.c.o
.PHONY : cpp/macro.c.o

cpp/macro.i: cpp/macro.c.i
.PHONY : cpp/macro.i

# target to preprocess a source file
cpp/macro.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/macro.c.i
.PHONY : cpp/macro.c.i

cpp/macro.s: cpp/macro.c.s
.PHONY : cpp/macro.s

# target to generate assembly for a file
cpp/macro.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/macro.c.s
.PHONY : cpp/macro.c.s

cpp/nlist.o: cpp/nlist.c.o
.PHONY : cpp/nlist.o

# target to build an object file
cpp/nlist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/nlist.c.o
.PHONY : cpp/nlist.c.o

cpp/nlist.i: cpp/nlist.c.i
.PHONY : cpp/nlist.i

# target to preprocess a source file
cpp/nlist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/nlist.c.i
.PHONY : cpp/nlist.c.i

cpp/nlist.s: cpp/nlist.c.s
.PHONY : cpp/nlist.s

# target to generate assembly for a file
cpp/nlist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/nlist.c.s
.PHONY : cpp/nlist.c.s

cpp/tokens.o: cpp/tokens.c.o
.PHONY : cpp/tokens.o

# target to build an object file
cpp/tokens.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/tokens.c.o
.PHONY : cpp/tokens.c.o

cpp/tokens.i: cpp/tokens.c.i
.PHONY : cpp/tokens.i

# target to preprocess a source file
cpp/tokens.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/tokens.c.i
.PHONY : cpp/tokens.c.i

cpp/tokens.s: cpp/tokens.c.s
.PHONY : cpp/tokens.s

# target to generate assembly for a file
cpp/tokens.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/tokens.c.s
.PHONY : cpp/tokens.c.s

cpp/unix.o: cpp/unix.c.o
.PHONY : cpp/unix.o

# target to build an object file
cpp/unix.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/unix.c.o
.PHONY : cpp/unix.c.o

cpp/unix.i: cpp/unix.c.i
.PHONY : cpp/unix.i

# target to preprocess a source file
cpp/unix.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/unix.c.i
.PHONY : cpp/unix.c.i

cpp/unix.s: cpp/unix.c.s
.PHONY : cpp/unix.s

# target to generate assembly for a file
cpp/unix.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp.dir/build.make CMakeFiles/cpp.dir/cpp/unix.c.s
.PHONY : cpp/unix.c.s

dagcheck.o: dagcheck.c.o
.PHONY : dagcheck.o

# target to build an object file
dagcheck.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/dagcheck.c.o
.PHONY : dagcheck.c.o

dagcheck.i: dagcheck.c.i
.PHONY : dagcheck.i

# target to preprocess a source file
dagcheck.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/dagcheck.c.i
.PHONY : dagcheck.c.i

dagcheck.s: dagcheck.c.s
.PHONY : dagcheck.s

# target to generate assembly for a file
dagcheck.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/dagcheck.c.s
.PHONY : dagcheck.c.s

etc/gigatron-lcc.o: etc/gigatron-lcc.c.o
.PHONY : etc/gigatron-lcc.o

# target to build an object file
etc/gigatron-lcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/etc/gigatron-lcc.c.o
.PHONY : etc/gigatron-lcc.c.o

etc/gigatron-lcc.i: etc/gigatron-lcc.c.i
.PHONY : etc/gigatron-lcc.i

# target to preprocess a source file
etc/gigatron-lcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/etc/gigatron-lcc.c.i
.PHONY : etc/gigatron-lcc.c.i

etc/gigatron-lcc.s: etc/gigatron-lcc.c.s
.PHONY : etc/gigatron-lcc.s

# target to generate assembly for a file
etc/gigatron-lcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/etc/gigatron-lcc.c.s
.PHONY : etc/gigatron-lcc.c.s

etc/lcc.o: etc/lcc.c.o
.PHONY : etc/lcc.o

# target to build an object file
etc/lcc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/etc/lcc.c.o
.PHONY : etc/lcc.c.o

etc/lcc.i: etc/lcc.c.i
.PHONY : etc/lcc.i

# target to preprocess a source file
etc/lcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/etc/lcc.c.i
.PHONY : etc/lcc.c.i

etc/lcc.s: etc/lcc.c.s
.PHONY : etc/lcc.s

# target to generate assembly for a file
etc/lcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lcc.dir/build.make CMakeFiles/lcc.dir/etc/lcc.c.s
.PHONY : etc/lcc.c.s

gigatron.o: gigatron.c.o
.PHONY : gigatron.o

# target to build an object file
gigatron.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/gigatron.c.o
.PHONY : gigatron.c.o

gigatron.i: gigatron.c.i
.PHONY : gigatron.i

# target to preprocess a source file
gigatron.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/gigatron.c.i
.PHONY : gigatron.c.i

gigatron.s: gigatron.c.s
.PHONY : gigatron.s

# target to generate assembly for a file
gigatron.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/gigatron.c.s
.PHONY : gigatron.c.s

gigatron/mapsim/gtsim.o: gigatron/mapsim/gtsim.c.o
.PHONY : gigatron/mapsim/gtsim.o

# target to build an object file
gigatron/mapsim/gtsim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gtsim.dir/build.make CMakeFiles/gtsim.dir/gigatron/mapsim/gtsim.c.o
.PHONY : gigatron/mapsim/gtsim.c.o

gigatron/mapsim/gtsim.i: gigatron/mapsim/gtsim.c.i
.PHONY : gigatron/mapsim/gtsim.i

# target to preprocess a source file
gigatron/mapsim/gtsim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gtsim.dir/build.make CMakeFiles/gtsim.dir/gigatron/mapsim/gtsim.c.i
.PHONY : gigatron/mapsim/gtsim.c.i

gigatron/mapsim/gtsim.s: gigatron/mapsim/gtsim.c.s
.PHONY : gigatron/mapsim/gtsim.s

# target to generate assembly for a file
gigatron/mapsim/gtsim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gtsim.dir/build.make CMakeFiles/gtsim.dir/gigatron/mapsim/gtsim.c.s
.PHONY : gigatron/mapsim/gtsim.c.s

lburg/gram.o: lburg/gram.c.o
.PHONY : lburg/gram.o

# target to build an object file
lburg/gram.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/lburg/gram.c.o
.PHONY : lburg/gram.c.o

lburg/gram.i: lburg/gram.c.i
.PHONY : lburg/gram.i

# target to preprocess a source file
lburg/gram.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/lburg/gram.c.i
.PHONY : lburg/gram.c.i

lburg/gram.s: lburg/gram.c.s
.PHONY : lburg/gram.s

# target to generate assembly for a file
lburg/gram.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/lburg/gram.c.s
.PHONY : lburg/gram.c.s

lburg/lburg.o: lburg/lburg.c.o
.PHONY : lburg/lburg.o

# target to build an object file
lburg/lburg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/lburg/lburg.c.o
.PHONY : lburg/lburg.c.o

lburg/lburg.i: lburg/lburg.c.i
.PHONY : lburg/lburg.i

# target to preprocess a source file
lburg/lburg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/lburg/lburg.c.i
.PHONY : lburg/lburg.c.i

lburg/lburg.s: lburg/lburg.c.s
.PHONY : lburg/lburg.s

# target to generate assembly for a file
lburg/lburg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lburg.dir/build.make CMakeFiles/lburg.dir/lburg/lburg.c.s
.PHONY : lburg/lburg.c.s

mips.o: mips.c.o
.PHONY : mips.o

# target to build an object file
mips.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/mips.c.o
.PHONY : mips.c.o

mips.i: mips.c.i
.PHONY : mips.i

# target to preprocess a source file
mips.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/mips.c.i
.PHONY : mips.c.i

mips.s: mips.c.s
.PHONY : mips.s

# target to generate assembly for a file
mips.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/mips.c.s
.PHONY : mips.c.s

sparc.o: sparc.c.o
.PHONY : sparc.o

# target to build an object file
sparc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/sparc.c.o
.PHONY : sparc.c.o

sparc.i: sparc.c.i
.PHONY : sparc.i

# target to preprocess a source file
sparc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/sparc.c.i
.PHONY : sparc.c.i

sparc.s: sparc.c.s
.PHONY : sparc.s

# target to generate assembly for a file
sparc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/sparc.c.s
.PHONY : sparc.c.s

src/alloc.o: src/alloc.c.o
.PHONY : src/alloc.o

# target to build an object file
src/alloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/alloc.c.o
.PHONY : src/alloc.c.o

src/alloc.i: src/alloc.c.i
.PHONY : src/alloc.i

# target to preprocess a source file
src/alloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/alloc.c.i
.PHONY : src/alloc.c.i

src/alloc.s: src/alloc.c.s
.PHONY : src/alloc.s

# target to generate assembly for a file
src/alloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/alloc.c.s
.PHONY : src/alloc.c.s

src/bind.o: src/bind.c.o
.PHONY : src/bind.o

# target to build an object file
src/bind.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/bind.c.o
.PHONY : src/bind.c.o

src/bind.i: src/bind.c.i
.PHONY : src/bind.i

# target to preprocess a source file
src/bind.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/bind.c.i
.PHONY : src/bind.c.i

src/bind.s: src/bind.c.s
.PHONY : src/bind.s

# target to generate assembly for a file
src/bind.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/bind.c.s
.PHONY : src/bind.c.s

src/bytecode.o: src/bytecode.c.o
.PHONY : src/bytecode.o

# target to build an object file
src/bytecode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/bytecode.c.o
.PHONY : src/bytecode.c.o

src/bytecode.i: src/bytecode.c.i
.PHONY : src/bytecode.i

# target to preprocess a source file
src/bytecode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/bytecode.c.i
.PHONY : src/bytecode.c.i

src/bytecode.s: src/bytecode.c.s
.PHONY : src/bytecode.s

# target to generate assembly for a file
src/bytecode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/bytecode.c.s
.PHONY : src/bytecode.c.s

src/dag.o: src/dag.c.o
.PHONY : src/dag.o

# target to build an object file
src/dag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/dag.c.o
.PHONY : src/dag.c.o

src/dag.i: src/dag.c.i
.PHONY : src/dag.i

# target to preprocess a source file
src/dag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/dag.c.i
.PHONY : src/dag.c.i

src/dag.s: src/dag.c.s
.PHONY : src/dag.s

# target to generate assembly for a file
src/dag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/dag.c.s
.PHONY : src/dag.c.s

src/decl.o: src/decl.c.o
.PHONY : src/decl.o

# target to build an object file
src/decl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/decl.c.o
.PHONY : src/decl.c.o

src/decl.i: src/decl.c.i
.PHONY : src/decl.i

# target to preprocess a source file
src/decl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/decl.c.i
.PHONY : src/decl.c.i

src/decl.s: src/decl.c.s
.PHONY : src/decl.s

# target to generate assembly for a file
src/decl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/decl.c.s
.PHONY : src/decl.c.s

src/enode.o: src/enode.c.o
.PHONY : src/enode.o

# target to build an object file
src/enode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/enode.c.o
.PHONY : src/enode.c.o

src/enode.i: src/enode.c.i
.PHONY : src/enode.i

# target to preprocess a source file
src/enode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/enode.c.i
.PHONY : src/enode.c.i

src/enode.s: src/enode.c.s
.PHONY : src/enode.s

# target to generate assembly for a file
src/enode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/enode.c.s
.PHONY : src/enode.c.s

src/error.o: src/error.c.o
.PHONY : src/error.o

# target to build an object file
src/error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/error.c.o
.PHONY : src/error.c.o

src/error.i: src/error.c.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/error.c.i
.PHONY : src/error.c.i

src/error.s: src/error.c.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/error.c.s
.PHONY : src/error.c.s

src/event.o: src/event.c.o
.PHONY : src/event.o

# target to build an object file
src/event.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/event.c.o
.PHONY : src/event.c.o

src/event.i: src/event.c.i
.PHONY : src/event.i

# target to preprocess a source file
src/event.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/event.c.i
.PHONY : src/event.c.i

src/event.s: src/event.c.s
.PHONY : src/event.s

# target to generate assembly for a file
src/event.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/event.c.s
.PHONY : src/event.c.s

src/expr.o: src/expr.c.o
.PHONY : src/expr.o

# target to build an object file
src/expr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/expr.c.o
.PHONY : src/expr.c.o

src/expr.i: src/expr.c.i
.PHONY : src/expr.i

# target to preprocess a source file
src/expr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/expr.c.i
.PHONY : src/expr.c.i

src/expr.s: src/expr.c.s
.PHONY : src/expr.s

# target to generate assembly for a file
src/expr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/expr.c.s
.PHONY : src/expr.c.s

src/gen.o: src/gen.c.o
.PHONY : src/gen.o

# target to build an object file
src/gen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/gen.c.o
.PHONY : src/gen.c.o

src/gen.i: src/gen.c.i
.PHONY : src/gen.i

# target to preprocess a source file
src/gen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/gen.c.i
.PHONY : src/gen.c.i

src/gen.s: src/gen.c.s
.PHONY : src/gen.s

# target to generate assembly for a file
src/gen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/gen.c.s
.PHONY : src/gen.c.s

src/init.o: src/init.c.o
.PHONY : src/init.o

# target to build an object file
src/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/init.c.o
.PHONY : src/init.c.o

src/init.i: src/init.c.i
.PHONY : src/init.i

# target to preprocess a source file
src/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/init.c.i
.PHONY : src/init.c.i

src/init.s: src/init.c.s
.PHONY : src/init.s

# target to generate assembly for a file
src/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/init.c.s
.PHONY : src/init.c.s

src/inits.o: src/inits.c.o
.PHONY : src/inits.o

# target to build an object file
src/inits.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/inits.c.o
.PHONY : src/inits.c.o

src/inits.i: src/inits.c.i
.PHONY : src/inits.i

# target to preprocess a source file
src/inits.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/inits.c.i
.PHONY : src/inits.c.i

src/inits.s: src/inits.c.s
.PHONY : src/inits.s

# target to generate assembly for a file
src/inits.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/inits.c.s
.PHONY : src/inits.c.s

src/input.o: src/input.c.o
.PHONY : src/input.o

# target to build an object file
src/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/input.c.o
.PHONY : src/input.c.o

src/input.i: src/input.c.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/input.c.i
.PHONY : src/input.c.i

src/input.s: src/input.c.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/input.c.s
.PHONY : src/input.c.s

src/lex.o: src/lex.c.o
.PHONY : src/lex.o

# target to build an object file
src/lex.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/lex.c.o
.PHONY : src/lex.c.o

src/lex.i: src/lex.c.i
.PHONY : src/lex.i

# target to preprocess a source file
src/lex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/lex.c.i
.PHONY : src/lex.c.i

src/lex.s: src/lex.c.s
.PHONY : src/lex.s

# target to generate assembly for a file
src/lex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/lex.c.s
.PHONY : src/lex.c.s

src/list.o: src/list.c.o
.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i
.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s
.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/list.c.s
.PHONY : src/list.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/main.c.s
.PHONY : src/main.c.s

src/null.o: src/null.c.o
.PHONY : src/null.o

# target to build an object file
src/null.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/null.c.o
.PHONY : src/null.c.o

src/null.i: src/null.c.i
.PHONY : src/null.i

# target to preprocess a source file
src/null.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/null.c.i
.PHONY : src/null.c.i

src/null.s: src/null.c.s
.PHONY : src/null.s

# target to generate assembly for a file
src/null.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/null.c.s
.PHONY : src/null.c.s

src/output.o: src/output.c.o
.PHONY : src/output.o

# target to build an object file
src/output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/output.c.o
.PHONY : src/output.c.o

src/output.i: src/output.c.i
.PHONY : src/output.i

# target to preprocess a source file
src/output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/output.c.i
.PHONY : src/output.c.i

src/output.s: src/output.c.s
.PHONY : src/output.s

# target to generate assembly for a file
src/output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/output.c.s
.PHONY : src/output.c.s

src/prof.o: src/prof.c.o
.PHONY : src/prof.o

# target to build an object file
src/prof.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/prof.c.o
.PHONY : src/prof.c.o

src/prof.i: src/prof.c.i
.PHONY : src/prof.i

# target to preprocess a source file
src/prof.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/prof.c.i
.PHONY : src/prof.c.i

src/prof.s: src/prof.c.s
.PHONY : src/prof.s

# target to generate assembly for a file
src/prof.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/prof.c.s
.PHONY : src/prof.c.s

src/profio.o: src/profio.c.o
.PHONY : src/profio.o

# target to build an object file
src/profio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/profio.c.o
.PHONY : src/profio.c.o

src/profio.i: src/profio.c.i
.PHONY : src/profio.i

# target to preprocess a source file
src/profio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/profio.c.i
.PHONY : src/profio.c.i

src/profio.s: src/profio.c.s
.PHONY : src/profio.s

# target to generate assembly for a file
src/profio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/profio.c.s
.PHONY : src/profio.c.s

src/simp.o: src/simp.c.o
.PHONY : src/simp.o

# target to build an object file
src/simp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/simp.c.o
.PHONY : src/simp.c.o

src/simp.i: src/simp.c.i
.PHONY : src/simp.i

# target to preprocess a source file
src/simp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/simp.c.i
.PHONY : src/simp.c.i

src/simp.s: src/simp.c.s
.PHONY : src/simp.s

# target to generate assembly for a file
src/simp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/simp.c.s
.PHONY : src/simp.c.s

src/stab.o: src/stab.c.o
.PHONY : src/stab.o

# target to build an object file
src/stab.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/stab.c.o
.PHONY : src/stab.c.o

src/stab.i: src/stab.c.i
.PHONY : src/stab.i

# target to preprocess a source file
src/stab.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/stab.c.i
.PHONY : src/stab.c.i

src/stab.s: src/stab.c.s
.PHONY : src/stab.s

# target to generate assembly for a file
src/stab.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/stab.c.s
.PHONY : src/stab.c.s

src/stmt.o: src/stmt.c.o
.PHONY : src/stmt.o

# target to build an object file
src/stmt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/stmt.c.o
.PHONY : src/stmt.c.o

src/stmt.i: src/stmt.c.i
.PHONY : src/stmt.i

# target to preprocess a source file
src/stmt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/stmt.c.i
.PHONY : src/stmt.c.i

src/stmt.s: src/stmt.c.s
.PHONY : src/stmt.s

# target to generate assembly for a file
src/stmt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/stmt.c.s
.PHONY : src/stmt.c.s

src/string.o: src/string.c.o
.PHONY : src/string.o

# target to build an object file
src/string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/string.c.o
.PHONY : src/string.c.o

src/string.i: src/string.c.i
.PHONY : src/string.i

# target to preprocess a source file
src/string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/string.c.i
.PHONY : src/string.c.i

src/string.s: src/string.c.s
.PHONY : src/string.s

# target to generate assembly for a file
src/string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/string.c.s
.PHONY : src/string.c.s

src/sym.o: src/sym.c.o
.PHONY : src/sym.o

# target to build an object file
src/sym.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/sym.c.o
.PHONY : src/sym.c.o

src/sym.i: src/sym.c.i
.PHONY : src/sym.i

# target to preprocess a source file
src/sym.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/sym.c.i
.PHONY : src/sym.c.i

src/sym.s: src/sym.c.s
.PHONY : src/sym.s

# target to generate assembly for a file
src/sym.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/sym.c.s
.PHONY : src/sym.c.s

src/symbolic.o: src/symbolic.c.o
.PHONY : src/symbolic.o

# target to build an object file
src/symbolic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/symbolic.c.o
.PHONY : src/symbolic.c.o

src/symbolic.i: src/symbolic.c.i
.PHONY : src/symbolic.i

# target to preprocess a source file
src/symbolic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/symbolic.c.i
.PHONY : src/symbolic.c.i

src/symbolic.s: src/symbolic.c.s
.PHONY : src/symbolic.s

# target to generate assembly for a file
src/symbolic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/symbolic.c.s
.PHONY : src/symbolic.c.s

src/trace.o: src/trace.c.o
.PHONY : src/trace.o

# target to build an object file
src/trace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/trace.c.o
.PHONY : src/trace.c.o

src/trace.i: src/trace.c.i
.PHONY : src/trace.i

# target to preprocess a source file
src/trace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/trace.c.i
.PHONY : src/trace.c.i

src/trace.s: src/trace.c.s
.PHONY : src/trace.s

# target to generate assembly for a file
src/trace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/trace.c.s
.PHONY : src/trace.c.s

src/tree.o: src/tree.c.o
.PHONY : src/tree.o

# target to build an object file
src/tree.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/tree.c.o
.PHONY : src/tree.c.o

src/tree.i: src/tree.c.i
.PHONY : src/tree.i

# target to preprocess a source file
src/tree.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/tree.c.i
.PHONY : src/tree.c.i

src/tree.s: src/tree.c.s
.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/tree.c.s
.PHONY : src/tree.c.s

src/types.o: src/types.c.o
.PHONY : src/types.o

# target to build an object file
src/types.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/types.c.o
.PHONY : src/types.c.o

src/types.i: src/types.c.i
.PHONY : src/types.i

# target to preprocess a source file
src/types.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/types.c.i
.PHONY : src/types.c.i

src/types.s: src/types.c.s
.PHONY : src/types.s

# target to generate assembly for a file
src/types.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/src/types.c.s
.PHONY : src/types.c.s

x86.o: x86.c.o
.PHONY : x86.o

# target to build an object file
x86.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/x86.c.o
.PHONY : x86.c.o

x86.i: x86.c.i
.PHONY : x86.i

# target to preprocess a source file
x86.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/x86.c.i
.PHONY : x86.c.i

x86.s: x86.c.s
.PHONY : x86.s

# target to generate assembly for a file
x86.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/x86.c.s
.PHONY : x86.c.s

x86linux.o: x86linux.c.o
.PHONY : x86linux.o

# target to build an object file
x86linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/x86linux.c.o
.PHONY : x86linux.c.o

x86linux.i: x86linux.c.i
.PHONY : x86linux.i

# target to preprocess a source file
x86linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/x86linux.c.i
.PHONY : x86linux.c.i

x86linux.s: x86linux.c.s
.PHONY : x86linux.s

# target to generate assembly for a file
x86linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rcc.dir/build.make CMakeFiles/rcc.dir/x86linux.c.s
.PHONY : x86linux.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... glcc-ready"
	@echo "... libc-cpu4"
	@echo "... libc-cpu5"
	@echo "... libc-cpu6"
	@echo "... libc-cpu7"
	@echo "... libcon1"
	@echo "... libcon_b"
	@echo "... libcon_h"
	@echo "... libcon_n"
	@echo "... libconx"
	@echo "... libsim"
	@echo "... map128k"
	@echo "... map32k"
	@echo "... map512k"
	@echo "... map64k"
	@echo "... mapconx"
	@echo "... mapsim"
	@echo "... cpp"
	@echo "... gtsim"
	@echo "... lburg"
	@echo "... lcc"
	@echo "... rcc"
	@echo "... alpha.o"
	@echo "... alpha.i"
	@echo "... alpha.s"
	@echo "... cpp/cpp.o"
	@echo "... cpp/cpp.i"
	@echo "... cpp/cpp.s"
	@echo "... cpp/eval.o"
	@echo "... cpp/eval.i"
	@echo "... cpp/eval.s"
	@echo "... cpp/getopt.o"
	@echo "... cpp/getopt.i"
	@echo "... cpp/getopt.s"
	@echo "... cpp/hideset.o"
	@echo "... cpp/hideset.i"
	@echo "... cpp/hideset.s"
	@echo "... cpp/include.o"
	@echo "... cpp/include.i"
	@echo "... cpp/include.s"
	@echo "... cpp/lex.o"
	@echo "... cpp/lex.i"
	@echo "... cpp/lex.s"
	@echo "... cpp/macro.o"
	@echo "... cpp/macro.i"
	@echo "... cpp/macro.s"
	@echo "... cpp/nlist.o"
	@echo "... cpp/nlist.i"
	@echo "... cpp/nlist.s"
	@echo "... cpp/tokens.o"
	@echo "... cpp/tokens.i"
	@echo "... cpp/tokens.s"
	@echo "... cpp/unix.o"
	@echo "... cpp/unix.i"
	@echo "... cpp/unix.s"
	@echo "... dagcheck.o"
	@echo "... dagcheck.i"
	@echo "... dagcheck.s"
	@echo "... etc/gigatron-lcc.o"
	@echo "... etc/gigatron-lcc.i"
	@echo "... etc/gigatron-lcc.s"
	@echo "... etc/lcc.o"
	@echo "... etc/lcc.i"
	@echo "... etc/lcc.s"
	@echo "... gigatron.o"
	@echo "... gigatron.i"
	@echo "... gigatron.s"
	@echo "... gigatron/mapsim/gtsim.o"
	@echo "... gigatron/mapsim/gtsim.i"
	@echo "... gigatron/mapsim/gtsim.s"
	@echo "... lburg/gram.o"
	@echo "... lburg/gram.i"
	@echo "... lburg/gram.s"
	@echo "... lburg/lburg.o"
	@echo "... lburg/lburg.i"
	@echo "... lburg/lburg.s"
	@echo "... mips.o"
	@echo "... mips.i"
	@echo "... mips.s"
	@echo "... sparc.o"
	@echo "... sparc.i"
	@echo "... sparc.s"
	@echo "... src/alloc.o"
	@echo "... src/alloc.i"
	@echo "... src/alloc.s"
	@echo "... src/bind.o"
	@echo "... src/bind.i"
	@echo "... src/bind.s"
	@echo "... src/bytecode.o"
	@echo "... src/bytecode.i"
	@echo "... src/bytecode.s"
	@echo "... src/dag.o"
	@echo "... src/dag.i"
	@echo "... src/dag.s"
	@echo "... src/decl.o"
	@echo "... src/decl.i"
	@echo "... src/decl.s"
	@echo "... src/enode.o"
	@echo "... src/enode.i"
	@echo "... src/enode.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/event.o"
	@echo "... src/event.i"
	@echo "... src/event.s"
	@echo "... src/expr.o"
	@echo "... src/expr.i"
	@echo "... src/expr.s"
	@echo "... src/gen.o"
	@echo "... src/gen.i"
	@echo "... src/gen.s"
	@echo "... src/init.o"
	@echo "... src/init.i"
	@echo "... src/init.s"
	@echo "... src/inits.o"
	@echo "... src/inits.i"
	@echo "... src/inits.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/lex.o"
	@echo "... src/lex.i"
	@echo "... src/lex.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/null.o"
	@echo "... src/null.i"
	@echo "... src/null.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/prof.o"
	@echo "... src/prof.i"
	@echo "... src/prof.s"
	@echo "... src/profio.o"
	@echo "... src/profio.i"
	@echo "... src/profio.s"
	@echo "... src/simp.o"
	@echo "... src/simp.i"
	@echo "... src/simp.s"
	@echo "... src/stab.o"
	@echo "... src/stab.i"
	@echo "... src/stab.s"
	@echo "... src/stmt.o"
	@echo "... src/stmt.i"
	@echo "... src/stmt.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
	@echo "... src/sym.o"
	@echo "... src/sym.i"
	@echo "... src/sym.s"
	@echo "... src/symbolic.o"
	@echo "... src/symbolic.i"
	@echo "... src/symbolic.s"
	@echo "... src/trace.o"
	@echo "... src/trace.i"
	@echo "... src/trace.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
	@echo "... src/types.o"
	@echo "... src/types.i"
	@echo "... src/types.s"
	@echo "... x86.o"
	@echo "... x86.i"
	@echo "... x86.s"
	@echo "... x86linux.o"
	@echo "... x86linux.i"
	@echo "... x86linux.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /d/working/vscode-projects/Reference_Project/Gigatron/gigatron-lcc-master/build/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

